// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductionManagement.Data;

#nullable disable

namespace ProductionManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ProductionManagement.Models.Material", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<decimal>("MinimalStock").HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                b.Property<decimal>("Quantity").HasColumnType("TEXT");
                b.Property<string>("UnitOfMeasure").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Materials");
            });

            modelBuilder.Entity("ProductionManagement.Models.Product", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Category").HasColumnType("TEXT");
                b.Property<string>("Description").HasColumnType("TEXT");
                b.Property<int>("MinimalStock").HasColumnType("INTEGER");
                b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                b.Property<int>("ProductionTimePerUnit").HasColumnType("INTEGER");
                b.Property<string>("Specifications").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Products");
            });

            modelBuilder.Entity("ProductionManagement.Models.ProductMaterial", b =>
            {
                b.Property<int>("ProductId").HasColumnType("INTEGER");
                b.Property<int>("MaterialId").HasColumnType("INTEGER");
                b.Property<decimal>("QuantityNeeded").HasColumnType("TEXT");
                b.HasKey("ProductId", "MaterialId");
                b.HasIndex("MaterialId");
                b.ToTable("ProductMaterials");
            });

            modelBuilder.Entity("ProductionManagement.Models.ProductionLine", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int?>("CurrentWorkOrderId").HasColumnType("INTEGER");
                b.Property<float>("EfficiencyFactor").HasColumnType("REAL");
                b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("ProductionLines");
            });

            modelBuilder.Entity("ProductionManagement.Models.WorkOrder", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("EstimatedEndDate").HasColumnType("TEXT");
                b.Property<int?>("ProductionLineId").HasColumnType("INTEGER");
                b.Property<int>("ProductId").HasColumnType("INTEGER");
                b.Property<int>("ProgressPercent").HasColumnType("INTEGER");
                b.Property<int>("Quantity").HasColumnType("INTEGER");
                b.Property<DateTime>("StartDate").HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("ProductId");
                b.HasIndex("ProductionLineId");
                b.ToTable("WorkOrders");
            });

            modelBuilder.Entity("ProductionManagement.Models.ProductMaterial", b =>
            {
                b.HasOne("ProductionManagement.Models.Material", "Material").WithMany("ProductMaterials").HasForeignKey("MaterialId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("ProductionManagement.Models.Product", "Product").WithMany("ProductMaterials").HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Material");
                b.Navigation("Product");
            });

            modelBuilder.Entity("ProductionManagement.Models.WorkOrder", b =>
            {
                b.HasOne("ProductionManagement.Models.ProductionLine", "ProductionLine").WithMany("WorkOrders").HasForeignKey("ProductionLineId").OnDelete(DeleteBehavior.SetNull);
                b.HasOne("ProductionManagement.Models.Product", "Product").WithMany("WorkOrders").HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Product");
                b.Navigation("ProductionLine");
            });

            modelBuilder.Entity("ProductionManagement.Models.Material", b =>
            {
                b.Navigation("ProductMaterials");
            });

            modelBuilder.Entity("ProductionManagement.Models.Product", b =>
            {
                b.Navigation("ProductMaterials");
                b.Navigation("WorkOrders");
            });

            modelBuilder.Entity("ProductionManagement.Models.ProductionLine", b =>
            {
                b.Navigation("CurrentWorkOrder");
                b.Navigation("WorkOrders");
            });
#pragma warning restore 612, 618
        }
    }
}
